version: '3.3'
services:
        db:
                container_name: db
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: 1234
                ports:
                        - 3306:3306
                volumes:
                      - db-data:/var/lib/mysql
        phpmyadmin:
               container_name: phpmyadmin
               image: phpmyadmin
               restart: always
               ports:
                       - 8080:80
               environment:
                       - PMA_ARBITRARY=1

        php-apache:
                container_name: php-apache
                build: 
                        context: .
                        dockerfile: Dockerfile
                depends_on:
                        - db
                volumes:
                        - .:/var/www/html
                ports:
                        - 80:80
volumes:
       db-data: